version: '3.5'

services:
 n8n:
    image: docker.n8n.io/n8nio/n8n:1.106.1
    container_name: n8n
    restart: unless-stopped
    networks:
       proxy:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.entrypoints=http"
      - "traefik.http.routers.n8n.rule=Host(`n8n.teplyshko.ru`)"
      - "traefik.http.middlewares.n8n-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.n8n.middlewares=n8n-https-redirect"
      - "traefik.http.routers.n8n-secure.entrypoints=https"
      - "traefik.http.routers.n8n-secure.rule=Host(`n8n.teplyshko.ru`)"
      - "traefik.http.routers.n8n-secure.tls=true"
      - "traefik.http.routers.n8n-secure.service=n8n"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.docker.network=proxy"
    environment:
      - N8N_HOST=n8n.teplyshko.ru
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.teplyshko.ru/
      - GENERIC_TIMEZONE=Asia/Krasnoyarsk
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_PROXY_HOPS=1
      - N8N_RUNNERS_ENABLED=true
networks:
  proxy:
    name: proxy
    external: true
volumes:
  n8n_data:
